name = "auth2"
main = "src/server.ts"
# main = "integration-test/test-server.ts"
compatibility_date = "2022-07-06"
node_compat = true

# Add your account_id here..
account_id = "0c8c22bdcd98c3dc6a35190650ef7906"

services = [{ binding = "TOKEN_SERVICE", service = "token-service-dev" }]

route = { pattern = "auth2.sesamy.dev/*", zone_id = "b56a76d859fe2ed6a8d77270cd2e8ba8" }

[vars]
IMAGE_PROXY_URL = "https://imgproxy.prod.sesamy.cloud"
ISSUER = "https://auth2.sesamy.dev/"
LOGIN2_URL = 'https://login2.sesamy.dev'
JWKS_URL = "https://token.sesamy.dev/.well-known/jwks.json"
READ_PERMISSION = "auth:read"
WRITE_PERMISSION = "auth:write"


[[r2_buckets]]
binding = 'AUTH_TEMPLATES'
preview_bucket_name = 'auth-templates'
bucket_name = 'auth-templates'


# [[d1_databases]]
# binding = "AUTH_DB"
# database_name = "auth2"
# database_id = "872f055e-d401-46a3-a0d0-fa00e66868b5"


[triggers]
crons = ["0 3 * * *"]

[env.production]
route = { pattern = "auth2.sesamy.com/*", zone_id = "b944b5871689ada6ce48e380968a06b5" }


account_id = "d684d0f34602a66c97de230566a2fa87"
workers_dev = true
services = [{ binding = "TOKEN_SERVICE", service = "token-service-prod" }]

[env.production.vars]
ISSUER = "https://auth2.sesamy.com/"
LOGIN2_URL = 'https://login2.sesamy.com'
JWKS_URL = "https://token.sesamy.com/.well-known/jwks.json"
READ_PERMISSION = 'auth:read'
WRITE_PERMISSION = 'auth:write'
IMAGE_PROXY_URL = "https://imgproxy.prod.sesamy.cloud"

[[env.production.r2_buckets]]
binding = 'AUTH_TEMPLATES'
preview_bucket_name = 'auth-templates'
bucket_name = 'auth-templates'

# [[env.production.d1_databases]]
# binding = "AUTH_DB"
# database_name = "auth2"
# database_id = "921e31d7-63d0-441d-b60c-df2d6756db44"


[env.production.triggers]
crons = ["0 3 * * *"]

[env.test.vars]
ISSUER = "https://example.com/"
LOGIN2_URL = 'https://login2.sesamy.com'
JWKS_URL = "https://example.com/.well-known/jwks.json"
READ_PERMISSION = 'auth:read'
WRITE_PERMISSION = 'auth:write'
IMAGE_PROXY_URL = "https://imgproxy.prod.sesamy.cloud"
